### ISSUE TITLE
Examples are out of date

### ISSUE THREAD

**Issue by raelb** [ElasticEmail/ElasticEmail.WebApiClient-csharp#1]
Hello,
The current API does not support a "Send" method. Only a SendAsync method. Please can you update the examples to show how to use SendAsync.

**Comment by ElasticEmail** [comment]
Hello,
Current API is not async - perhaps you meant the .NET Core version of our library which can be found here: https://github.com/ElasticEmail/ElasticEmail.WebApiClient-csharp-core.
However, that version's examples contain async code already.

Thank you for your help,
Elastic Email
